version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["gh-dependencies"]
    commit-message:
      include: scope
      prefix: "ci(deps)"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "mypy*"
        dependency-type: "indirect"
      - dependency-name: "types-enum34"
        dependency-type: "direct"
    labels: ["pip-dependencies"]
    commit-message:
      include: scope
      prefix: "pip(deps)"
